services:
  ldap:
    image: bitnami/openldap
    ports:
      - "1389:1389"
    environment:
      - LDAP_ROOT=dc=order,dc=services
    volumes:
      - type: bind
        source: ./infrastructure/ldap
        target: /ldifs