services:
  ldap:
    image: bitnami/openldap
    ports:
      - "1389:1389"
    environment:
      - LDAP_ROOT=dc=order,dc=services
    volumes:
      - type: bind
        source: ./infrastructure/ldap
        target: /ldifs

  keycloak:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - postgresql
    ports:
      - "80:8080"
        
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'


volumes:
  postgresql_data:
    driver: local