services:
  ldap:
    image: bitnami/openldap
    ports:
      - "1389:1389"
    environment:
      - LDAP_ROOT=dc=order,dc=services
    volumes:
      - type: bind
        source: ./infrastructure/ldap/ldifs
        target: /ldifs

  keycloak:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - postgresql
    ports:
      - "80:8080"
        
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
      
  keycloak-setup:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - keycloak
    restart: on-failure
    healthcheck:
      start_period: 120s
    command: >
      sh -c "/opt/bitnami/keycloak/bin/kcadm.sh config credentials --server http://keycloak:8080/auth --realm master --user user --password bitnami --config /tmp/kcadm.config &&
             /opt/bitnami/keycloak/bin/kcadm.sh create components -r master \
                -s 'name=\"Ldap\"' \
                -s parentId=master \
                -s providerId=ldap \
                -s providerType=org.keycloak.storage.UserStorageProvider \
                -s config.priority=[0] \
                -s config.fullSyncPeriod=[60] \
                -s 'config.editMode=[\"READ_ONLY\"]' \
                -s 'config.connectionUrl=[\"LDAP:\/\/ldap:1389\"]' \
                -s 'config.usersDn=[\"ou=people,dc=order,dc=services\"]' \
                -s 'config.uuidLDAPAttribute=[\"entryUUID\"]' \
                -s 'config.rdnLDAPAttribute=[\"uid\"]' \
                -s 'config.usernameLDAPAttribute=[\"uid\"]' \
                -s 'config.userObjectClasses=[\"inetOrgPerson,organizationalPerson\"]' \
                -s 'config.searchScope=[\"2\"]' \
                -s 'config.vendor=[\"other\"]' \
                -s 'config.authType=[\"none\"]' \
                --config /tmp/kcadm.config"
 
 #/opt/bitnami/keycloak/bin/kcadm.sh create components -r master \
 #               -s name=\"Ldap\" \
 #               -s parentId=master \
 #               -s providerId=ldap \
 #               -s providerType=org.keycloak.storage.UserStorageProvider \ 
 #               -s 'config.priority=[\"1\"]' \
 #               -s 'config.fullSyncPeriod=[\"60\"]' \
 #               -s 'config.changedSyncPeriod=[\"-1\"]' \
 #               -s 'config.cachePolicy=[\"DEFAULT\"]' \
 #               -s 'config.batchSizeForSync=[\"1000\"]' \
 #               -s 'config.syncRegistrations=[\"false\"]' \
 #               -s 'config.vendor=[\"other\"]' \
 ##               -s 'config.uuidLDAPAttribute=[\"entryUUID\"]' \
 #               -s 'config.userObjectClasses=[\"inetOrgPerson, organizationalPerson\"]' \
 #               -s 'config.usersDn=[\"ou=people,de=order,dc=services\"]' \
 #               -s 'config.searchScope=2' \
 #               -s 'config.authType=[\"none\"]' \
 #               --config /tmp/kcadm.config"
      
      
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'

#volumes:
#  postgresql_data:
#    driver: local