services:
  ldap:
    image: bitnami/openldap
    ports:
      - "1389:1389"
    environment:
      - LDAP_ROOT=dc=order,dc=services
    volumes:
      - type: bind
        source: ./infrastructure/ldap/ldifs
        target: /ldifs

  keycloak:
    image: docker.io/bitnami/keycloak:16
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgresql
    ports:
      - "80:8080"
        
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
      
  keycloak-setup:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      keycloak:
        condition: service_healthy
    restart: on-failure
    command: >
      sh -c "/opt/bitnami/keycloak/bin/kcadm.sh config credentials --server http://keycloak:8080/auth --realm master --user user --password bitnami --config /tmp/kcadm.config &&
            /opt/bitnami/keycloak/bin/kcadm.sh create components --realm master --file provisioning/user-federation/storage-provider-config.json --config /tmp/kcadm.config &&
            /opt/bitnami/keycloak/bin/kcadm.sh create components --realm master --file provisioning/user-federation/ldap-group-mapper.json --config /tmp/kcadm.config"
    volumes:
      - ./infrastructure/keycloak:/provisioning